/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:da74988e-90c0-4afd-a93d-3deabbe777b0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9cvBWdHRJ",
    "aws_user_pools_web_client_id": "7ccir2laek6gh9e6ascovviuq1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://k5fhhdbqjbcc7eh66n6vsevda4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5icahs56tzafjkjrdjy7x32k7y",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://q7mb2fx4wk.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
